## numpy数组使用

In [5]:
import numpy as np

In [6]:
a = np.array([1, 2, 3])
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(a.shape,b.shape,a.dtype,b.dtype)

(3,) (3, 3) int64 int64


### 结构数组

In [10]:
persontype = np.dtype({ 'names':['name', 'age', 'chinese', 'math', 'english'], 'formats':['S32','i', 'i', 'i', 'f']})
peoples = np.array([("ZhangFei",32,75,100, 90),("GuanYu",24,85,96,88.5), 
                    ("ZhaoYun",28,85,92,96.5),("HuangZhong",29,65,85,100)], dtype=persontype)
peoples

array([(b'ZhangFei', 32, 75, 100,  90. ), (b'GuanYu', 24, 85,  96,  88.5),
       (b'ZhaoYun', 28, 85,  92,  96.5),
       (b'HuangZhong', 29, 65,  85, 100. )],
      dtype=[('name', 'S32'), ('age', '<i4'), ('chinese', '<i4'), ('math', '<i4'), ('english', '<f4')])

In [11]:
ages = peoples[:]['age']
print(np.mean(ages))

28.25


### 连续数组的创建

In [13]:
x1 = np.arange(1,11,2)
x1

array([1, 3, 5, 7, 9])

In [14]:
x2 = np.linspace(1,9,5)
x2

array([1., 3., 5., 7., 9.])

#### 数组之间的运算

In [16]:
print(np.add(x1,x2))
print(np.subtract(x1,x2))
print(np.multiply(x1,x2))
print(np.divide(x1,x2))
print(np.power(x1,x2))
print(np.remainder(x1,x2))

[ 2.  6. 10. 14. 18.]
[0. 0. 0. 0. 0.]
[ 1.  9. 25. 49. 81.]
[1. 1. 1. 1. 1.]
[1.00000000e+00 2.70000000e+01 3.12500000e+03 8.23543000e+05
 3.87420489e+08]
[0. 0. 0. 0. 0.]


### 统计函数

In [18]:
a = np.array([[1, 3, 2], [4, 5, 6], [9, 8, 7]])
a

array([[1, 3, 2],
       [4, 5, 6],
       [9, 8, 7]])

#### 最大最小值

In [23]:
print(np.amax(a))
print(np.amax(a,0)) #axis=0 是跨行（纵向），axis=1 是跨列（横向）
print(np.amax(a,1))
print(np.amin(a,1))
print(np.ptp(a)) # 最大最小差值
print(np.ptp(a,0)) 

9
[9 8 7]
[3 6 9]
[1 4 7]
8
[8 5 5]


#### 统计数组的百分位数 percentile()\中位数 median()、平均数 mean()

In [25]:
print(np.percentile(a,50))
print(np.percentile(a,50,axis=0))

5.0
[4. 5. 6.]


In [28]:
print(np.mean(a))
print(np.mean(a,axis=0))
print(np.mean(a,axis=1))
print(np.median(a))
print(np.median(a,axis=0))
print(np.median(a,axis=1))

5.0
[4.66666667 5.33333333 5.        ]
[2. 5. 8.]
5.0
[4. 5. 6.]
[2. 5. 8.]


#### 加权平均值 average()\标准差 std()、方差 var()

In [30]:
a = np.array([1,2,3,4])
wts = np.array([1,2,3,4])
print(np.average(a))
print(np.average(a,weights=wts))

2.5
3.0


In [32]:
print(np.std(a))
print(np.var(a))

1.118033988749895
1.25


#### NumPy 排序

In [36]:
a = np.array([[4,3,2],[2,4,1]])
print(np.sort(a))
print(np.sort(a,axis=None))
print(np.sort(a,axis=0))

[[2 3 4]
 [1 2 4]]
[1 2 2 3 4 4]
[[2 3 1]
 [4 4 2]]
