In [1]:
from sklearn import preprocessing
import numpy as np

/opt/anaconda3/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
/opt/anaconda3/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


### 0-1,min_max规范化

In [22]:
# x = np.linspace(1,20,9)
# x = x.reshape(3,3)
# x

array([[ 1.   ,  3.375,  5.75 ],
       [ 8.125, 10.5  , 12.875],
       [15.25 , 17.625, 20.   ]])

In [27]:
x = np.array([[ 0., -3., 1.], [ 3., 1., 2.], [ 0., 1., -1.]])
x

array([[ 0., -3.,  1.],
       [ 3.,  1.,  2.],
       [ 0.,  1., -1.]])

In [31]:
min_max_sclaer = preprocessing.MinMaxScaler(feature_range=(0,1))

In [32]:
min_max_sclaer.fit_transform(x)

array([[0.        , 0.        , 0.66666667],
       [1.        , 1.        , 1.        ],
       [0.        , 1.        , 0.        ]])

### Z-Score 规范化

In [33]:
zScore_x = preprocessing.scale(x)
zScore_x

array([[-0.70710678, -1.41421356,  0.26726124],
       [ 1.41421356,  0.70710678,  1.06904497],
       [-0.70710678,  0.70710678, -1.33630621]])

### 小数定标规范化

In [35]:
j = np.ceil(np.log10(np.max(abs(x))))
j


1.0

In [36]:
x/(10**j)

array([[ 0. , -0.3,  0.1],
       [ 0.3,  0.1,  0.2],
       [ 0. ,  0.1, -0.1]])