In [13]:
# 使用K-means对图像进行聚类，并显示聚类压缩后的图像
import numpy as np
import PIL.Image as image
from sklearn.cluster import KMeans
from sklearn import preprocessing
import matplotlib.image as mping

### 加载数据

In [14]:
f= open('./data/kmeans-master/weixin.jpg','rb')
data =[]
img = image.open(f)

# 得到图像尺寸
width ,height = img.size
# 得到点(x,y)的三个通道值
for x in range(width):
    for y in range(height):
        c1,c2,c3 = img.getpixel((x,y))
        data.append([c1,c2,c3])
        
f.close()

In [24]:
img.size

(100, 177)

In [15]:
data

[[0, 0, 0],
 [0, 0, 0],
 [0, 0, 0],
 [0, 0, 0],
 [0, 0, 0],
 [0, 0, 0],
 [0, 0, 0],
 [0, 0, 0],
 [0, 0, 0],
 [0, 0, 0],
 [0, 0, 0],
 [0, 0, 0],
 [1, 1, 1],
 [1, 1, 1],
 [1, 1, 1],
 [1, 1, 1],
 [1, 1, 1],
 [1, 1, 1],
 [1, 1, 1],
 [0, 2, 1],
 [0, 1, 3],
 [0, 1, 3],
 [0, 2, 3],
 [0, 2, 3],
 [0, 0, 2],
 [0, 0, 2],
 [0, 0, 2],
 [0, 0, 2],
 [0, 0, 2],
 [0, 0, 2],
 [0, 0, 2],
 [0, 0, 2],
 [0, 0, 0],
 [0, 0, 2],
 [1, 1, 3],
 [1, 1, 3],
 [0, 1, 3],
 [0, 1, 5],
 [1, 2, 6],
 [1, 2, 6],
 [0, 3, 6],
 [0, 3, 6],
 [0, 3, 6],
 [0, 4, 7],
 [0, 4, 7],
 [0, 3, 8],
 [1, 4, 9],
 [1, 4, 9],
 [1, 2, 7],
 [1, 2, 7],
 [0, 3, 8],
 [0, 3, 8],
 [0, 3, 10],
 [1, 4, 11],
 [0, 5, 11],
 [0, 5, 11],
 [2, 5, 12],
 [2, 5, 12],
 [2, 5, 12],
 [2, 7, 13],
 [2, 7, 13],
 [2, 6, 15],
 [3, 7, 16],
 [3, 7, 16],
 [0, 7, 15],
 [0, 7, 15],
 [1, 8, 16],
 [1, 8, 18],
 [2, 9, 19],
 [1, 10, 19],
 [1, 10, 19],
 [1, 10, 19],
 [2, 10, 21],
 [2, 10, 21],
 [3, 11, 22],
 [3, 11, 22],
 [3, 11, 24],
 [2, 12, 24],
 [2, 12, 24],
 [2, 12, 24],
 

In [17]:
mm = preprocessing.MinMaxScaler()

In [18]:
data_mm = mm.fit_transform(data)
data_mm

array([[0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        ],
       ...,
       [0.00865801, 0.04310345, 0.08606557],
       [0.00865801, 0.04310345, 0.08606557],
       [0.00865801, 0.04310345, 0.08606557]])

### 模型

In [20]:
data_mat = np.mat(data_mm)
data_mat

matrix([[0.        , 0.        , 0.        ],
        [0.        , 0.        , 0.        ],
        [0.        , 0.        , 0.        ],
        ...,
        [0.00865801, 0.04310345, 0.08606557],
        [0.00865801, 0.04310345, 0.08606557],
        [0.00865801, 0.04310345, 0.08606557]])

In [28]:
# 用K-Means对图像进行2聚类
kmeans2 = KMeans(n_clusters=2)
kmeans2.fit(data_mat)
label2 = kmeans2.predict(data_mat)

In [29]:
label2

array([0, 0, 0, ..., 0, 0, 0], dtype=int32)

In [30]:
# 将图像聚类结果，转化成图像尺寸的矩阵
label2 = label2.reshape([width,height])
label2

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int32)

In [31]:
# 创建个新图像pic_mark，用来保存图像聚类的结果，并设置不同的灰度值
pic_kmeans2 = image.new("L",(width,height))
for x in range(width):
    for y in range(height):
        pic_kmeans2.putpixel((x,y),int(256/(label2[x][y]+1))-1)
pic_kmeans2.save('./data/kmeans-master/pic_kmeans2.jpg','JPEG')

In [32]:
# 用K-Means对图像进行16聚类
kmeans16 = KMeans(n_clusters=16)
kmeans16.fit(data_mat)
label16 = kmeans16.predict(data_mat)
label16

array([6, 6, 6, ..., 0, 0, 0], dtype=int32)

In [39]:
# 将图像聚类结果，转化成图像尺寸的矩阵
label16 = label16.reshape([width,height])
label16

array([[6, 6, 6, ..., 0, 0, 0],
       [6, 6, 6, ..., 0, 0, 0],
       [6, 6, 6, ..., 0, 0, 0],
       ...,
       [6, 6, 6, ..., 0, 0, 0],
       [6, 6, 6, ..., 0, 0, 0],
       [6, 6, 6, ..., 0, 0, 0]], dtype=int32)

In [36]:
from skimage import color

In [37]:
# 将聚类标识矩阵转化为不同颜色的矩阵a
label_color = (color.label2rgb(label16)*255).astype(np.uint8)
label_color = label_color.transpose(1,0,2)
images = image.fromarray(label_color)
images.save('./data/kmeans-master/pic_kmeans16.jpg','JPEG')

In [40]:
kmeans16.cluster_centers_

array([[0.00970797, 0.04426949, 0.08633895],
       [0.66578119, 0.72337872, 0.75633383],
       [0.30067856, 0.41461341, 0.53816155],
       [0.02694721, 0.10535285, 0.1935562 ],
       [0.58087864, 0.65201784, 0.70176346],
       [0.829994  , 0.86688791, 0.86648291],
       [0.00177563, 0.00729113, 0.01641125],
       [0.08964385, 0.21150883, 0.35535955],
       [0.40842094, 0.50354064, 0.60233704],
       [0.05743785, 0.15435064, 0.26457867],
       [0.49703065, 0.58111073, 0.65413239],
       [0.08423445, 0.12318749, 0.16740689],
       [0.02175961, 0.07369211, 0.1319873 ],
       [0.74209406, 0.79156013, 0.81164039],
       [0.92376037, 0.94599834, 0.92841291],
       [0.17467159, 0.30413942, 0.45134963]])

In [41]:
# 创建个新图像img，用来保存图像聚类压缩后的结果
img_kemans16= image.new("RGB",(width,height))
for x in range(width):
    for y in range(height):
        c1 = kmeans16.cluster_centers_[label16[x, y], 0]
        c2 = kmeans16.cluster_centers_[label16[x, y], 1]
        c3 = kmeans16.cluster_centers_[label16[x, y], 2]
        img_kemans16.putpixel((x,y), (int(c1*256)-1, int(c2*256)-1, int(c3*256)-1))
img_kemans16.save("./data/kmeans-master/img_kemans16.jpg")